0 CLS:PRINTCHR$(13);"   HEADER1 for the CoCo 1 & 2"
1 PRINTCHR$(32);STRING$(29,42)
2 PRINTCHR$(32);CHR$(42);"     Music Sheet Paper     ";CHR$(42)
3 PRINTCHR$(32);CHR$(42);"      For the DMP-105      ";CHR$(42)
4 PRINTCHR$(32);CHR$(42);"     by Barry McNeice      ";CHR$(42)
5 PRINTCHR$(32);CHR$(42);"         Yakima, WA        ";CHR$(42)
6 PRINTCHR$(32);CHR$(42);"     (c) Falsoft, Inc.     ";CHR$(42)
7 PRINTCHR$(32);CHR$(42);" The Rainbow June'86 pg.20 ";CHR$(42)
8 PRINTCHR$(32);STRING$(29,42)
9 PRINTSTRING$(5,13);STRING$(10,32);"Press a Key";:EXEC 44539
